import { bibliography } from '../bibliography';
import type { ToolLocaleContent } from '../../../types';
import type { StepperDriverMicrosteppingCalculatorUI } from '../ui';

export const content: ToolLocaleContent<StepperDriverMicrosteppingCalculatorUI> = {
  slug: 'stepper-driver-microstepping-calculator',
  title: 'Stepper Motor Steps per MM & Microstepping Calculator',
  description: 'Calculate the exact steps per mm (or steps/inch) and theoretical mechanical resolution for 3D printer stepper motors. Supports TMC2209, TMC2208, belts, and lead screws.',
  ui: {
    title: 'Stepper Driver Microstepping Calculator',
    presetsLabel: 'PRESETS',
    presetBelt16: 'GT2 Belt & 16T Pulley (X/Y)',
    presetBelt20: 'GT2 Belt & 20T Pulley (X/Y)',
    presetZLead8: 'T8 Lead Screw 8mm Lead (Z)',
    presetZLead2: 'T8 Lead Screw 2mm Lead (Z)',
    unitSystemLabel: 'Unit System',
    metricLabel: 'Metric',
    imperialLabel: 'Imperial',
    configLabel: 'MOTOR & DRIVER CONFIGURATION',
    motorStepAngleLabel: 'Motor Step Angle',
    driverMicrosteppingLabel: 'Driver Microstepping',
    transmissionModeLabel: 'Transmission Type',
    transmissionBelt: 'Belt Drive',
    transmissionLeadScrew: 'Lead Screw / Threaded Rod',
    beltPitchLabel: 'Belt Pitch',
    pulleyTeethLabel: 'Pulley Teeth',
    leadScrewPitchLabel: 'Lead Screw Lead (Distance per Rev)',
    resultsLabel: 'CALCULATED OUTPUTS',
    stepsPerUnitLabel: 'Firmware Configuration (Steps)',
    mechanicalResolutionLabel: 'Theoretical Resolution',
    stepsPerUnitUnitMetric: 'steps/mm',
    stepsPerUnitUnitImperial: 'steps/inch',
    mechanicalResolutionUnitMetric: 'microns/step',
    mechanicalResolutionUnitImperial: 'thou/step',
    formulaLabel: 'MATHEMATICAL FORMULAS',
    formulaStepsPerRevolution: 'Steps/Rev = 360 / Step Angle',
    formulaMicrostepsPerRev: 'Microsteps/Rev = Steps/Rev * Microsteps',
    formulaDistancePerRev: 'Distance/Rev = Teeth * Pitch (or Lead Screw Lead)',
    formulaStepsPerUnit: 'Steps/Unit = Microsteps/Rev / Distance/Rev',
    formulaResolution: 'Resolution = Distance/Rev / Microsteps/Rev',
    explainResolutionLabel: 'What does this mean?',
    explainResolutionText: 'This represents the smallest theoretical linear movement your 3D printer axis can make when the stepper driver commands a single microstep. Lower resolution values indicate finer mechanical positioning precision.',
    copyButton: 'Copy Firmware Command',
    copiedButton: 'Copied!',
    stepAngleUnit: '°',
    microstepsUnit: 'x',
    pitchUnitMetric: 'mm',
    pitchUnitImperial: 'in',
    teethUnit: 'teeth',
    stepAngle18: '1.8° (200 steps/rev)',
    stepAngle09: '0.9° (400 steps/rev)',
    stepAngle75: '7.5° (48 steps/rev)',
    stepAngle15: '15° (24 steps/rev)',
    microstep1: '1x (Full Step)',
    microstep2: '2x',
    microstep4: '4x',
    microstep8: '8x',
    microstep16: '16x',
    microstep32: '32x',
    microstep64: '64x',
    microstep128: '128x',
    microstep256: '256x',
  },
  seo: [
    {
      type: 'title',
      text: 'Stepper Motor Calibration and Firmware Steps per Millimeter Configuration Guide',
      level: 2,
    },
    {
      type: 'paragraph',
      html: 'In consumer and professional-grade 3D printers, precision motion control relies on stepper motors, stepper drivers, and linear transmission mechanisms. Stepper motors do not rotate continuously; instead, they divide a full rotation into a set number of discrete steps. For the 3D printer controller board to move the print head or print bed by an exact distance, the firmware must know precisely how many motor steps (including microsteps) correspond to one unit of linear distance (millimeter or inch). This value is known as the steps per millimeter or steps per inch, and it is a critical setting stored in firmware configurations like Marlin, Klipper, or RepRapFirmware.',
    },
    {
      type: 'paragraph',
      html: 'If this configuration is even slightly incorrect, the physical movements of the 3D printer will not match the digital instructions generated by the slicer software. This mismatch leads to dimensional inaccuracy in printed objects, where parts end up larger or smaller than intended, holes are misaligned, and multi-part assemblies fail to fit together. Understanding the physical components, driver characteristics, and transmission ratios allows operators to calculate mathematically perfect values rather than relying on trial-and-error calibration methods that introduce mechanical errors.',
    },
    {
      type: 'title',
      text: 'Comparing Stepper Motor Specifications and Mechanical Attributes',
      level: 2,
    },
    {
      type: 'paragraph',
      html: 'The most common stepper motors used in 3D printing are hybrid stepper motors in the NEMA 17 form factor. These motors typically come in two step angle variations: 1.8 degrees per step and 0.9 degrees per step. A 1.8-degree stepper motor requires 200 full steps to complete one full 360-degree rotation. A 0.9-degree stepper motor requires 400 full steps to complete the same rotation. Choosing between these specifications affects the positioning accuracy, maximum torque, and operational noise of the printing system.',
    },
    {
      type: 'comparative',
      items: [
        {
          title: '1.8 Degree Stepper Motor',
          description: 'Standard motor option for most commercial 3D printers. Offers robust torque at higher speeds and is economical.',
          points: [
            '200 full steps per revolution',
            'Higher high-speed torque retention',
            'Lower electrical inductance requirements',
            'Sufficient resolution for general FDM applications'
          ]
        },
        {
          title: '0.9 Degree Stepper Motor',
          description: 'High-precision motor option popular for fine-detail printers and high-resolution extruder systems.',
          points: [
            '400 full steps per revolution',
            'Double the mechanical resolution before microstepping',
            'Reduced positional error and lower resonance vibrations',
            'Higher back-EMF at high speeds reduces torque limit'
          ]
        }
      ],
      columns: 2,
    },
    {
      type: 'paragraph',
      html: 'While a 0.9-degree motor offers double the physical positioning capability, it demands twice as many step pulses from the motherboard microcontroller to achieve the same rotational speed. For high-speed printing platforms running on older 8-bit microcontrollers, this can saturate the processing queue and cause print stutters or speed limitations. On modern 32-bit controllers, this limitation is rarely an issue, making 0.9-degree motors an excellent upgrade for X and Y axes where surface finish is critical.',
    },
    {
      type: 'title',
      text: 'Glossary of Stepper Motor and Driver Terminologies',
      level: 2,
    },
    {
      type: 'glossary',
      items: [
        {
          term: 'Step Angle',
          definition: 'The angular rotation of the motor shaft when a single full step coil excitation sequence occurs, typically 1.8 degrees or 0.9 degrees.',
        },
        {
          term: 'Microstepping',
          definition: 'A method controlled by the stepper driver that divides a single full step into smaller sub-steps by balancing current between the motor phases, smoothing motion and reducing vibration.',
        },
        {
          term: 'Belt Pitch',
          definition: 'The distance between the centers of two adjacent teeth on a synchronous timing belt, commonly 2.0 millimeters for GT2 belts used in 3D printing.',
        },
        {
          term: 'Lead Screw Lead',
          definition: 'The linear distance that a nut travels along the lead screw during one full 360-degree rotation of the screw shaft.',
        },
        {
          term: 'Holding Torque',
          definition: 'The maximum amount of torque that the motor can exert on a stationary shaft when rated current is applied to the coils.',
        },
        {
          term: 'Back Electromotive Force (Back-EMF)',
          definition: 'The voltage generated by the rotation of the motor coils inside the magnetic field, which opposes the supply voltage and limits maximum speed and torque.',
        }
      ],
    },
    {
      type: 'title',
      text: 'Calculating Steps per Millimeter for Timing Belts',
      level: 2,
    },
    {
      type: 'paragraph',
      html: 'For the horizontal motion axes (usually X and Y) of Cartesian, CoreXY, and Delta 3D printers, synchronous timing belts are utilized to convert rotational motion from the stepper motor into linear movement. The mechanical calculation depends entirely on the belt pitch and the number of teeth on the drive pulley attached to the motor shaft. The belt tooth profile must match the pulley tooth profile to prevent backlash and slip.',
    },
    {
      type: 'table',
      headers: ['Pulley Size', 'Belt Type', 'Belt Pitch', 'Steps/rev (1.8 deg, 16x)', 'Steps per MM (Metric)', 'Steps per Inch (Imperial)'],
      rows: [
        ['16 Teeth', 'GT2', '2.0 mm', '3200', '100.00 steps/mm', '2540.00 steps/in'],
        ['20 Teeth', 'GT2', '2.0 mm', '3200', '80.00 steps/mm', '2032.00 steps/in'],
        ['32 Teeth', 'GT2', '2.0 mm', '3200', '50.00 steps/mm', '1270.00 steps/in'],
        ['20 Teeth', 'GT3', '3.0 mm', '3200', '53.33 steps/mm', '1354.67 steps/in'],
        ['16 Teeth (0.9 deg)', 'GT2', '2.0 mm', '6400', '200.00 steps/mm', '5080.00 steps/in'],
        ['20 Teeth (0.9 deg)', 'GT2', '2.0 mm', '6400', '160.00 steps/mm', '4064.00 steps/in']
      ],
    },
    {
      type: 'tip',
      title: 'Practical Design Choice for Pulley Selection',
      html: 'Choosing a 16-tooth pulley instead of a 20-tooth pulley increases mechanical resolution by 25 percent and increases the linear force exerted on the carriage. However, smaller pulleys force the timing belt to bend around a tighter radius, which can increase belt wear over time and introduce higher vibration frequencies. For standard builds, 20-tooth pulleys represent a balanced compromise between belt lifespan and resolution.',
    },
    {
      type: 'title',
      text: 'Microstepping Realities: Torque Losses and the Interpolation Solution',
      level: 2,
    },
    {
      type: 'paragraph',
      html: 'Many operators believe that increasing the driver microstepping resolution to high values like 64, 128, or 256 will infinitely scale the accuracy of their 3D printer. This is a common misconception. In reality, the incremental torque between microsteps drops off drastically as the microstepping division increases. The electrical current is divided into sine and cosine curves to position the motor shaft between physical poles. If the external friction or load on the axis exceeds the incremental torque of a microstep, the motor shaft will fail to move until several microstep pulses have accumulated.',
    },
    {
      type: 'diagnostic',
      variant: 'warning',
      title: 'Theoretical vs Physical Microstepping Torque Limitation',
      html: 'At 16 microsteps, the incremental torque per microstep is approximately 9.8 percent of the motor holding torque. At 256 microsteps, the incremental torque drops to just 0.6 percent of the holding torque. Any small mechanical binding, belt tension imbalance, or carriage friction will easily prevent physical motion of 1/256th of a step, meaning high native microstepping does not guarantee real positional accuracy.',
    },
    {
      type: 'card',
      title: 'Trinamic Driver Interpolation Feature',
      html: 'Modern stepper drivers like the TMC2208, TMC2209, and TMC5160 solve this problem by receiving step commands at a reliable 16 microsteps resolution and internally interpolating those steps to 256 microsteps before executing the coil current changes. This provides the smooth, quiet operation of 256 microsteps while maintaining the reliable holding torque and reduced controller processing overhead of 16 microsteps configuration. In firmware, keep your configuration at 16 microsteps and let the driver handle the internal interpolation.',
    },
    {
      type: 'title',
      text: 'Calculating Steps per Millimeter for Z-Axis Lead Screws and Rods',
      level: 2,
    },
    {
      type: 'paragraph',
      html: 'The vertical Z-axis of most desktop 3D printers uses lead screws or threaded rods. Lead screws are designed for power transmission and have precision-ground thread profiles that minimize backlash. When calculating steps per mm for a lead screw, the pitch of the screw threads must not be confused with the lead. The lead is the actual linear distance traveled by the lead screw nut during one complete 360-degree rotation of the screw. The lead is calculated by multiplying the thread pitch by the number of thread starts.',
    },
    {
      type: 'list',
      items: [
        'Single-start Lead Screw: Pitch is 2mm, starts count is 1. The lead is 2mm per revolution.',
        'Two-start Lead Screw: Pitch is 2mm, starts count is 2. The lead is 4mm per revolution.',
        'Four-start Lead Screw (Common T8x8): Pitch is 2mm, starts count is 4. The lead is 8mm per revolution.',
        'Standard Metric Threaded Rods (e.g. M8): Single start. Lead is equal to standard metric pitch, which is 1.25mm per revolution.'
      ],
    },
    {
      type: 'paragraph',
      html: 'Because lead screws have a mechanical advantage over belt-driven systems, they achieve much higher steps per mm values, indicating smaller mechanical resolution values. This high resolution is critical for Z-axes because layers are typically printed at increments between 0.1mm and 0.3mm. A higher steps per mm value allows the printer to establish consistent layer heights without positioning errors.',
    },
    {
      type: 'title',
      text: 'Summary of Key Steps for Driver and Motor Integration',
      level: 2,
    },
    {
      type: 'summary',
      title: 'Actionable Steps to Configure Your Printer firmware',
      items: [
        'Identify motor step angle from the manufacturer datasheet (usually 1.8 or 0.9 degrees).',
        'Determine driver microstepping settings configured via physical jumpers or software UART commands (16 is recommended).',
        'Measure or lookup the belt pitch and count the pulley teeth for belt axes.',
        'Verify the lead screw lead (pitch times starts count) for the Z axis.',
        'Input these parameters into our calculator to obtain the exact steps/mm or steps/inch configuration value.',
        'Write the calculated values to your firmware configuration files or save them using terminal commands like M92.'
      ],
    },
  ],
  faq: [
    {
      question: 'Why is my calculated steps/mm different from my manual calibration result?',
      answer: 'Calculated steps/mm are mathematically exact based on physical component geometry. If a manual calibration suggests a different value, it is usually because the operator measured filament or axis travel with a caliper while mechanical play, belt stretch, or extruder slippage introduced errors. You should always use the mathematically calculated value for motion axes and fix the underlying mechanical issues instead.',
    },
    {
      question: 'What happens if I set the microstepping value too high in firmware?',
      answer: 'Setting the microstepping value to 64, 128, or 256 in firmware increases the pulse frequency demand on your controller board. If the motherboard cannot generate step pulses fast enough, the printer may freeze, stutter, or limit the maximum travel speed. It is best to use 16 microsteps in firmware with driver-level interpolation enabled.',
    },
    {
      question: 'How do I change the steps per mm settings on my 3D printer?',
      answer: 'You can change the values temporarily using the M92 command followed by the axis letter and the value (e.g., M92 X80.00 Y80.00 Z400.00). To make these values permanent, send the M500 command to save them to the EEPROM, or edit the Configuration.h file in Marlin firmware and reflash, or edit the printer.cfg file in Klipper.',
    },
    {
      question: 'What is the difference between belt pitch and pulley teeth?',
      answer: 'Belt pitch is the distance between two teeth on the belt, measured from center to center. Pulley teeth is the total number of physical teeth on the gear attached to the motor shaft. Multiplying the teeth count by the pitch gives the total linear distance traveled per motor revolution.',
    },
    {
      question: 'Can I use different microstepping values for different axes?',
      answer: 'Yes, you can configure different microstepping values for X, Y, Z, and E axes. For example, it is very common to run X and Y at 16 microsteps, Z at 16 microsteps, and the extruder at 16 or 32 microsteps depending on the gear ratio of the extruder assembly.',
    }
  ],
  bibliography,
  howTo: [
    {
      name: 'Determine Motor and Driver Specs',
      text: 'Find your motor step angle (typically 1.8 or 0.9 degrees) and your driver microstepping value (16 is standard).',
    },
    {
      name: 'Determine Transmission Details',
      text: 'Choose between belt drive (specify belt pitch and pulley teeth) and lead screw (specify screw lead).',
    },
    {
      name: 'Configure Firmware Settings',
      text: 'Input the values, select your preferred unit system, and copy the generated steps configuration command into your printer config.',
    },
  ],
  schemas: [
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'Why is my calculated steps/mm different from my manual calibration result?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Calculated steps/mm are mathematically exact based on physical component geometry. Manual calibration often introduces errors due to belt tension or filament compression.',
          },
        },
      ],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Stepper Driver Microstepping Calculator',
      description: 'Calculate step configuration values and physical resolution limits for 3D printer motors and drivers.',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'All',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'HowTo',
      name: 'How to calculate stepper motor steps per mm',
      step: [
        {
          '@type': 'HowToStep',
          text: 'Determine Motor and Driver Specs',
        },
        {
          '@type': 'HowToStep',
          text: 'Determine Transmission Details',
        },
        {
          '@type': 'HowToStep',
          text: 'Configure Firmware Settings',
        },
      ],
    },
  ],
};
